#!/usr/bin/env bash
set -euo pipefail

CONTAINER_NAME=kaggle-m5-$(shuf -er -n8 {a..z} | tr -d '\n')

get-port () {
    sleep 2
    printf "\nhttp://$(docker port $CONTAINER_NAME 8787)\n\r\n"
}

if [ -z "$*" ]
then
    USER_ARG="--user root"
    get-port &

else
    USER_ARG="--user rstudio"
fi

docker run \
-it --rm \
--name $CONTAINER_NAME \
$USER_ARG \
-e DISABLE_AUTH=true \
-p "127.0.0.1:0:8787" \
-v "$(pwd)":/home/rstudio \
kyuss-caesar/kaggle-m5:latest \
"$@"
