redo-always

# remote _site.yml; it's generated by _site.yml.do
if [ -f _site.yml ]
then

  R --slave >&2 <<EOF
rmarkdown::clean_site()
EOF

  rm _site.yml
fi

# remove any .html leftover
find . -type f -name '*.html' -exec rm {} \;

