redo-always

# remove _site.yml; it's generated by _site.yml.do
if [ -f _site.yml ]
then

  R --slave >&2 <<EOF
rmarkdown::clean_site()
EOF

  rm _site.yml
fi

# remove any .html leftover
find . -mindepth 1 -maxdepth 1 -type f -name '*.html' -exec rm {} \;

# remove any _cache or _files leftover
find . -mindepth 1 -maxdepth 1 -type d -name '*_files' -or -name '*_cache' -exec rm -rf {} \;

